# Generated by Django 6.1 on 2026-08-13 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Razón Social')),
                ('trade_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre Comercial')),
                ('tax_id', models.CharField(max_length=20, unique=True, verbose_name='Identificación Fiscal / RUC')),
                ('address', models.TextField(verbose_name='Dirección Matriz')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('is_accounting_required', models.BooleanField(default=True, verbose_name='Obligado a llevar Contabilidad')),
                ('special_taxpayer_resolution', models.CharField(blank=True, max_length=50, null=True, verbose_name='Resolución Contribuyente Especial')),
                ('is_rimpe', models.BooleanField(default=False, verbose_name='Régimen RIMPE')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='companies/logos/', verbose_name='Logo de la Empresa')),
                ('is_active', models.BooleanField(default=True, verbose_name='Empresa Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyUserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrador'), ('ACCOUNTANT', 'Contador'), ('VIEWER', 'Solo Lectura')], default='ACCOUNTANT', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='companies.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permiso de Usuario en Empresa',
                'verbose_name_plural': 'Permisos de Usuarios en Empresas',
                'unique_together': {('user', 'company')},
            },
        ),
    ]
