# Generated by Django 6.1 on 2026-08-13 18:49

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Código Decimal (ej: 1.1.01.001)')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la Cuenta')),
                ('account_type', models.CharField(choices=[('ASSET', 'Activo'), ('LIABILITY', 'Pasivo'), ('EQUITY', 'Patrimonio'), ('INCOME', 'Ingresos'), ('EXPENSE', 'Gastos')], max_length=20, verbose_name='Naturaleza de Cuenta')),
                ('kind', models.CharField(choices=[('CONTROL', 'Título / Agrupadora'), ('MOVEMENT', 'Movimiento / Detalle')], default='MOVEMENT', max_length=20, verbose_name='Tipo de Cuenta')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='companies.company')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounting.account', verbose_name='Cuenta Padre')),
            ],
            options={
                'verbose_name': 'Cuenta Contable',
                'verbose_name_plural': 'Cuentas Contables',
                'ordering': ['code'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Año Fiscal')),
                ('start_date', models.DateField(verbose_name='Fecha Inicio')),
                ('end_date', models.DateField(verbose_name='Fecha Fin')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Cerrado')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_years', to='companies.company')),
            ],
            options={
                'verbose_name': 'Año Fiscal',
                'verbose_name_plural': 'Años Fiscales',
                'ordering': ['-year'],
                'unique_together': {('company', 'year')},
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_number', models.PositiveIntegerField(verbose_name='Número de Asiento')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('entry_type', models.CharField(choices=[('GENERAL', 'Diario / Ajuste'), ('SALE', 'Venta'), ('PURCHASE', 'Compra'), ('PAYMENT', 'Cobro / Pago'), ('OPENING', 'Apertura'), ('CLOSING', 'Cierre')], default='GENERAL', max_length=20, verbose_name='Tipo de Comprobante')),
                ('concept', models.TextField(verbose_name='Concepto / Glosa')),
                ('reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Documento / Referencia')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('POSTED', 'Asentado / Publicado'), ('CANCELLED', 'Anulado')], default='DRAFT', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='accounting.fiscalyear')),
            ],
            options={
                'verbose_name': 'Asiento Contable',
                'verbose_name_plural': 'Asientos Contables',
                'ordering': ['-date', '-entry_number'],
                'unique_together': {('company', 'fiscal_year', 'entry_number')},
            },
        ),
        migrations.CreateModel(
            name='JournalEntryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.CharField(blank=True, max_length=200, null=True, verbose_name='Detalle de Línea')),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Debe / Débito')),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Haber / Crédito')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='accounting.account')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.journalentry')),
            ],
            options={
                'verbose_name': 'Línea de Asiento',
                'verbose_name_plural': 'Líneas de Asiento',
            },
        ),
    ]
