# Generated by Django 6.1 on 2026-08-13 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceNumbering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_number', models.PositiveIntegerField(default=1, verbose_name='Próximo Número de Referencia')),
                ('prefix', models.CharField(blank=True, max_length=10, null=True, verbose_name='Prefijo de Referencia (ej: REF-)')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_numbering', to='companies.company')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_numbering', to='accounting.fiscalyear')),
            ],
            options={
                'verbose_name': 'Numeración de Referencia',
                'verbose_name_plural': 'Numeraciones de Referencia',
                'ordering': ['-fiscal_year'],
                'unique_together': {('company', 'fiscal_year')},
            },
        ),
    ]
