# Generated by Django 6.1 on 2026-08-31 17:33

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_referencenumbering'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntryTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la Plantilla')),
                ('entry_type', models.CharField(choices=[('GENERAL', 'Diario / Ajuste'), ('SALE', 'Venta'), ('PURCHASE', 'Compra'), ('PAYMENT', 'Cobro / Pago'), ('OPENING', 'Apertura'), ('CLOSING', 'Cierre')], default='GENERAL', max_length=20, verbose_name='Tipo de Comprobante')),
                ('concept', models.TextField(verbose_name='Concepto / Glosa')),
                ('reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Documento / Referencia (opcional)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_templates', to='companies.company')),
            ],
            options={
                'verbose_name': 'Plantilla de Asiento',
                'verbose_name_plural': 'Plantillas de Asiento',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntryTemplateLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.CharField(blank=True, max_length=200, null=True, verbose_name='Detalle de Línea')),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Debe / Débito')),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Haber / Crédito')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='template_lines', to='accounting.account')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.journalentrytemplate')),
            ],
            options={
                'verbose_name': 'Línea de Plantilla',
                'verbose_name_plural': 'Líneas de Plantilla',
            },
        ),
    ]
