# Generated by Django 6.1 on 2026-08-13 18:49

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('CLIENT', 'Cliente'), ('SUPPLIER', 'Proveedor'), ('BOTH', 'Cliente / Proveedor')], default='CLIENT', max_length=20, verbose_name='Tipo de Contacto')),
                ('id_type', models.CharField(choices=[('RUC', 'RUC (Ecuador)'), ('CEDULA', 'Cédula de Identidad'), ('PASSPORT', 'Pasaporte')], default='RUC', max_length=20, verbose_name='Tipo Documento')),
                ('id_number', models.CharField(max_length=20, verbose_name='Número de Documento / RUC')),
                ('name', models.CharField(max_length=200, verbose_name='Razón Social / Nombre')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='companies.company')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'ordering': ['name'],
                'unique_together': {('company', 'id_number')},
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_type', models.CharField(choices=[('SALE', 'Factura de Venta'), ('PURCHASE', 'Factura de Compra')], max_length=20, verbose_name='Tipo de Factura')),
                ('invoice_number', models.CharField(max_length=50, verbose_name='Número de Factura (ej: 001-001-000000001)')),
                ('sri_authorization', models.CharField(blank=True, max_length=49, null=True, verbose_name='Clave de Acceso / Autorización SRI')),
                ('issue_date', models.DateField(verbose_name='Fecha de Emisión')),
                ('due_date', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('ISSUED', 'Emitida / Asentada'), ('PAID', 'Pagada'), ('CANCELLED', 'Anulada')], default='DRAFT', max_length=20, verbose_name='Estado')),
                ('subtotal_15', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Subtotal IVA 15%')),
                ('subtotal_0', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Subtotal IVA 0%')),
                ('vat_15', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='IVA 15%')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Total Factura')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='companies.company')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='invoicing.contact', verbose_name='Cliente / Proveedor')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='accounting.journalentry', verbose_name='Asiento Contable Generado')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-issue_date', '-invoice_number'],
                'unique_together': {('company', 'invoice_type', 'invoice_number')},
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250, verbose_name='Descripción de Producto/Servicio')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Precio Unitario')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5, verbose_name='Tarifa IVA %')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Subtotal')),
                ('vat_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Monto IVA')),
                ('total', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Total Linea')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoicing.invoice')),
            ],
            options={
                'verbose_name': 'Detalle de Factura',
                'verbose_name_plural': 'Detalles de Facturas',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(verbose_name='Fecha de Pago')),
                ('payment_method', models.CharField(choices=[('CASH', 'Efectivo / Caja Chica'), ('BANK_TRANSFER', 'Transferencia Bancaria'), ('CHECK', 'Cheque'), ('CARD', 'Tarjeta de Crédito / Débito')], default='BANK_TRANSFER', max_length=30, verbose_name='Forma de Pago')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Monto Pagado')),
                ('reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nro. Comprobante / Transferencia')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.account', verbose_name='Cuenta de Caja / Banco')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='companies.company')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='invoicing.invoice', verbose_name='Factura Afectada')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to='accounting.journalentry', verbose_name='Asiento Contable de Pago')),
            ],
            options={
                'verbose_name': 'Pago / Cobro',
                'verbose_name_plural': 'Pagos / Cobros',
                'ordering': ['-payment_date'],
            },
        ),
    ]
